services:
  - type: web
    name: ussd-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: AFRICAS_TALKING_API_KEY
        sync: false
      - key: AFRICAS_TALKING_USERNAME
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false